### ISSUE TITLE
OEM comm protocol download

### ISSUE THREAD

**Issue by djalizae** [mckenm/HanmaTekPSUCmd#2]
Not sure if anyone has seen it, but just wanted to post a link from the etommens.com website which has Communication protocol (SP series_SPL series_SPV series_SPD series) in a RAR file.  Might be useful for saving time on development.

http://www.etommens.com/uploadfile/file/20200119/20200119091837_2143016715.rar

**Comment by mckenm** [comment]
Thanks for sharing
